name: Create README on push
on:
  push:
    branches:
      - main
jobs:
  create-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create README file
        run: |
          # Create a README file in the main/doc/ directory within the repository
          echo "Hello World" > main/doc/README.md
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Create README file"
          git push origin main
